[package]
name = "tanuki-mpris"
edition.workspace = true
version.workspace = true

[dependencies]
tanuki.workspace = true

anyhow = "1.0.100"
clap   = { version = "4.5.56", features = ["derive"] }
mpris  = "2.0.1"
tokio  = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
